# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNMobileCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNMobileCenter
  pod 'RNMobileCenter', '~> 0.5.0'
  pod 'MobileCenter', '~> 0.9.0'

  

  target 'RNMobileCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNMobileCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNMobileCenter-tvOS

  target 'RNMobileCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
